apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: anilsiripipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anilsiripipelinesjavascriptdocker 
    spec:
      containers:
        - name: anilsiripipelinesjavascriptdocker 
          image: anilsiri80cr.azurecr.io/anilsiripipelinesjavascriptdockerold
          ports:
          - containerPort: 8080
